create table if not exists baseline_expression_log (
    targetId LowCardinality (String),
    targetFromSourceId Nullable (String),
    tissueBiosampleId Nullable (String),
    tissueBiosampleParentId Nullable (String),
    tissueBiosampleFromSource Nullable (String),
    celltypeBiosampleId Nullable (String),
    celltypeBiosampleParentId Nullable (String),
    celltypeBiosampleFromSource Nullable (String),
    min Nullable (Float64),
    q1 Nullable (Float64),
    median Nullable (Float64),
    q3 Nullable (Float64),
    max Nullable (Float64),
    distribution_score Float64,
    specificity_score Nullable (Float64),
    datasourceId String,
    datatypeId String,
    unit String,
    qualityControls Array (String)
) engine = Log;
